In [18]:
import torch
import numpy as np

In [73]:
groundtruth = [['A'], ['A', 'B'], ['A', 'B', 'C']]
predictions = [['A'], ['B', 'C'], ['A', 'C']]

In [74]:
from collections import defaultdict

correct_counter = defaultdict(int)
prediction_counter = defaultdict(int)
groundtruth_counter = defaultdict(int)

In [75]:
for pred_labels, true_labels in zip(predictions, groundtruth):
    for p in pred_labels:
        if p in true_labels:
            correct_counter[p] += 1
        prediction_counter[p] += 1
    for t in true_labels:
        groundtruth_counter[t] += 1

In [76]:
correct_counter

defaultdict(int, {'A': 2, 'B': 1, 'C': 1})

In [77]:
prediction_counter

defaultdict(int, {'A': 2, 'B': 1, 'C': 2})

In [78]:
groundtruth_counter

defaultdict(int, {'A': 3, 'B': 2, 'C': 1})

In [79]:
micro_precision = sum(correct_counter.values()) / sum(prediction_counter.values())
micro_precision

0.8

In [80]:
micro_recall = sum(correct_counter.values()) / sum(groundtruth_counter.values())
micro_recall

0.6666666666666666

In [81]:
macro_types_precision = {t: correct_counter[t]/prediction_counter[t] for t in ['A', 'B', 'C']}
macro_types_precision

{'A': 1.0, 'B': 1.0, 'C': 0.5}

In [82]:
macro_types_precision = np.mean(list(macro_types_precision.values()))
macro_types_precision

0.8333333333333334

In [83]:
macro_types_recall = {t: correct_counter[t]/groundtruth_counter[t] for t in ['A', 'B', 'C']}
macro_types_recall

{'A': 0.6666666666666666, 'B': 0.5, 'C': 1.0}

In [84]:
macro_types_recall = np.mean(list(macro_types_recall.values()))
macro_types_recall

0.7222222222222222

In [85]:
macro_examples_precision = [len(set(p).intersection(set(t)))/len(p) for p, t in zip(predictions, groundtruth)]
macro_examples_precision

[1.0, 0.5, 1.0]

In [86]:
macro_examples_precision = np.mean(macro_examples_precision)
macro_examples_precision

0.8333333333333334

In [87]:
macro_examples_recall = [len(set(p).intersection(set(t)))/len(t) for p, t in zip(predictions, groundtruth)]
macro_examples_recall

[1.0, 0.5, 0.6666666666666666]

In [88]:
macro_examples_recall = np.mean(macro_examples_recall)
macro_examples_recall

0.7222222222222222

In [30]:
groundtruth = [['A'], ['A', 'B'], ['A', 'B', 'C']]
predictions = [['A'], ['B', 'C'], ['A', 'C']]

one_h_groundtruth = torch.tensor([[1, 0, 0], [1, 1, 0], [1, 1, 1]])
one_h_predictions = torch.tensor([[1, 0, 0], [0, 1, 1], [1, 0, 1]])

In [31]:
one_h_sum = one_h_groundtruth + one_h_predictions
one_h_dif = one_h_groundtruth - one_h_predictions

In [32]:
one_h_sum

tensor([[2, 0, 0],
        [1, 2, 1],
        [2, 1, 2]])

In [33]:
one_h_dif

tensor([[ 0,  0,  0],
        [ 1,  0, -1],
        [ 0,  1,  0]])

In [37]:
correct + torch.sum(one_h_dif == -1)

tensor(5)

In [40]:
correct = torch.sum(one_h_sum == 2)
predicted = correct + torch.sum(one_h_dif == -1)
groundtruth = correct + torch.sum(one_h_dif == 1)
micro_precision_tensor = correct/predicted
micro_precision_tensor

tensor(0.8000)

In [41]:
micro_recall_tensor = correct/groundtruth
micro_recall_tensor

tensor(0.6667)

In [55]:
torch.sum(one_h_sum == 2, dim=0) + torch.sum(one_h_dif == 1, dim=0)

tensor([3, 2, 1])

In [56]:
predicted_types = torch.sum(one_h_sum == 2, dim=0) + torch.sum(one_h_dif == -1, dim=0)
correct_types = torch.sum(one_h_sum == 2, dim = 0)
groundtruth_types = torch.sum(one_h_sum == 2, dim=0) + torch.sum(one_h_dif == 1, dim=0)

In [57]:
predicted_types

tensor([2, 1, 2])

In [58]:
correct_types

tensor([2, 1, 1])

In [59]:
groundtruth_types

tensor([3, 2, 1])

In [62]:
macro_types_precision_tensor = torch.mean(correct_types/predicted_types)
macro_types_precision_tensor

tensor(0.8333)

In [63]:
macro_types_recall_tensor = torch.mean(correct_types/groundtruth_types)
macro_types_recall_tensor

tensor(0.7222)

In [64]:
predicted_examples = torch.sum(one_h_sum == 2, dim=1) + torch.sum(one_h_dif == -1, dim=1)
correct_examples = torch.sum(one_h_sum == 2, dim = 1)
groundtruth_examples = torch.sum(one_h_sum == 2, dim=1) + torch.sum(one_h_dif == 1, dim=1)

In [65]:
predicted_examples

tensor([1, 2, 2])

In [66]:
correct_examples

tensor([1, 1, 2])

In [67]:
groundtruth_examples

tensor([1, 2, 3])

In [69]:
macro_examples_precision_tensor = torch.mean(correct_examples/predicted_examples)
macro_examples_precision_tensor

tensor(0.8333)

In [70]:
macro_examples_recall_tensor = torch.mean(correct_examples/groundtruth_examples)
macro_examples_recall_tensor

tensor(0.7222)

In [103]:
torch.sum(torch.sum(torch.tensor([[0, 1], [0, 1], [0, 1]]), dim = 0) > 0)

tensor(1)

In [101]:
torch.sum(torch.sum(torch.tensor([[1, 1], [0, 1], [0, 1]]), dim = 0) > 0)

tensor(2)